# fly.toml app configuration file generated for saasgit on 2025-03-06T12:10:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saasgit'
primary_region = 'lhr'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
