services:
  - type: web
    name: nextjs-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables as needed
    autoDeploy: true 